/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

(* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:3.1-148.10" *)
(* top =  1  *)
(* hdlname = "adc_digital" *)
module adc_digital(seq_init, seq_samp, seq_comp, seq_update, en_init, en_samp_p, en_samp_n, en_comp, en_update, dac_mode, dac_astate_p, dac_bstate_p, dac_astate_n, dac_bstate_n, dac_diffcaps, comp_out_p, comp_out_n, clk_samp_p, clk_samp_p_b, clk_samp_n, clk_samp_n_b
, clk_comp, dac_state_p_main, dac_state_p_diff, dac_state_n_main, dac_state_n_diff, comp_out);
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:6.17-6.25" *)
  input seq_init;
  wire seq_init;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:7.17-7.25" *)
  input seq_samp;
  wire seq_samp;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:8.17-8.25" *)
  input seq_comp;
  wire seq_comp;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:9.17-9.27" *)
  input seq_update;
  wire seq_update;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:12.17-12.24" *)
  input en_init;
  wire en_init;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:13.17-13.26" *)
  input en_samp_p;
  wire en_samp_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:14.17-14.26" *)
  input en_samp_n;
  wire en_samp_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:15.17-15.24" *)
  input en_comp;
  wire en_comp;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:16.17-16.26" *)
  input en_update;
  wire en_update;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:19.17-19.25" *)
  input dac_mode;
  wire dac_mode;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:20.24-20.36" *)
  input [15:0] dac_astate_p;
  wire [15:0] dac_astate_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:21.24-21.36" *)
  input [15:0] dac_bstate_p;
  wire [15:0] dac_bstate_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:24.24-24.36" *)
  input [15:0] dac_astate_n;
  wire [15:0] dac_astate_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:25.24-25.36" *)
  input [15:0] dac_bstate_n;
  wire [15:0] dac_bstate_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:28.16-28.28" *)
  input dac_diffcaps;
  wire dac_diffcaps;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:30.17-30.27" *)
  input comp_out_p;
  wire comp_out_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:30.29-30.39" *)
  input comp_out_n;
  wire comp_out_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:33.17-33.27" *)
  output clk_samp_p;
  wire clk_samp_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:33.29-33.41" *)
  output clk_samp_p_b;
  wire clk_samp_p_b;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:34.17-34.27" *)
  output clk_samp_n;
  wire clk_samp_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:34.29-34.41" *)
  output clk_samp_n_b;
  wire clk_samp_n_b;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:37.17-37.25" *)
  output clk_comp;
  wire clk_comp;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:40.24-40.40" *)
  output [15:0] dac_state_p_main;
  wire [15:0] dac_state_p_main;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:41.24-41.40" *)
  output [15:0] dac_state_p_diff;
  wire [15:0] dac_state_p_diff;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:42.24-42.40" *)
  output [15:0] dac_state_n_main;
  wire [15:0] dac_state_n_main;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:43.24-43.40" *)
  output [15:0] dac_state_n_diff;
  wire [15:0] dac_state_n_diff;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:46.17-46.25" *)
  output comp_out;
  wire comp_out;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:57.10-57.18" *)
  wire clk_init;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:58.26-58.40" *)
  wire clk_samp_n_raw;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:58.10-58.24" *)
  wire clk_samp_p_raw;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:59.10-59.20" *)
  wire clk_update;
  BUFFD0LVT _00_ (
    .I(comp_out_p),
    .Z(comp_out)
  );
  BUFFD0LVT _01_ (
    .I(dac_state_n_diff[0]),
    .Z(dac_state_n_main[0])
  );
  BUFFD0LVT _02_ (
    .I(dac_state_n_diff[1]),
    .Z(dac_state_n_main[1])
  );
  BUFFD0LVT _03_ (
    .I(dac_state_n_diff[2]),
    .Z(dac_state_n_main[2])
  );
  BUFFD0LVT _04_ (
    .I(dac_state_n_diff[3]),
    .Z(dac_state_n_main[3])
  );
  BUFFD0LVT _05_ (
    .I(dac_state_n_diff[4]),
    .Z(dac_state_n_main[4])
  );
  BUFFD0LVT _06_ (
    .I(dac_state_n_diff[5]),
    .Z(dac_state_n_main[5])
  );
  BUFFD0LVT _07_ (
    .I(dac_state_n_diff[6]),
    .Z(dac_state_n_main[6])
  );
  BUFFD0LVT _08_ (
    .I(dac_state_n_diff[7]),
    .Z(dac_state_n_main[7])
  );
  BUFFD0LVT _09_ (
    .I(dac_state_n_diff[8]),
    .Z(dac_state_n_main[8])
  );
  BUFFD0LVT _10_ (
    .I(dac_state_n_diff[9]),
    .Z(dac_state_n_main[9])
  );
  BUFFD0LVT _11_ (
    .I(dac_state_n_diff[10]),
    .Z(dac_state_n_main[10])
  );
  BUFFD0LVT _12_ (
    .I(dac_state_n_diff[11]),
    .Z(dac_state_n_main[11])
  );
  BUFFD0LVT _13_ (
    .I(dac_state_n_diff[12]),
    .Z(dac_state_n_main[12])
  );
  BUFFD0LVT _14_ (
    .I(dac_state_n_diff[13]),
    .Z(dac_state_n_main[13])
  );
  BUFFD0LVT _15_ (
    .I(dac_state_n_diff[14]),
    .Z(dac_state_n_main[14])
  );
  BUFFD0LVT _16_ (
    .I(dac_state_n_diff[15]),
    .Z(dac_state_n_main[15])
  );
  BUFFD0LVT _17_ (
    .I(dac_state_p_diff[0]),
    .Z(dac_state_p_main[0])
  );
  BUFFD0LVT _18_ (
    .I(dac_state_p_diff[1]),
    .Z(dac_state_p_main[1])
  );
  BUFFD0LVT _19_ (
    .I(dac_state_p_diff[2]),
    .Z(dac_state_p_main[2])
  );
  BUFFD0LVT _20_ (
    .I(dac_state_p_diff[3]),
    .Z(dac_state_p_main[3])
  );
  BUFFD0LVT _21_ (
    .I(dac_state_p_diff[4]),
    .Z(dac_state_p_main[4])
  );
  BUFFD0LVT _22_ (
    .I(dac_state_p_diff[5]),
    .Z(dac_state_p_main[5])
  );
  BUFFD0LVT _23_ (
    .I(dac_state_p_diff[6]),
    .Z(dac_state_p_main[6])
  );
  BUFFD0LVT _24_ (
    .I(dac_state_p_diff[7]),
    .Z(dac_state_p_main[7])
  );
  BUFFD0LVT _25_ (
    .I(dac_state_p_diff[8]),
    .Z(dac_state_p_main[8])
  );
  BUFFD0LVT _26_ (
    .I(dac_state_p_diff[9]),
    .Z(dac_state_p_main[9])
  );
  BUFFD0LVT _27_ (
    .I(dac_state_p_diff[10]),
    .Z(dac_state_p_main[10])
  );
  BUFFD0LVT _28_ (
    .I(dac_state_p_diff[11]),
    .Z(dac_state_p_main[11])
  );
  BUFFD0LVT _29_ (
    .I(dac_state_p_diff[12]),
    .Z(dac_state_p_main[12])
  );
  BUFFD0LVT _30_ (
    .I(dac_state_p_diff[13]),
    .Z(dac_state_p_main[13])
  );
  BUFFD0LVT _31_ (
    .I(dac_state_p_diff[14]),
    .Z(dac_state_p_main[14])
  );
  BUFFD0LVT _32_ (
    .I(dac_state_p_diff[15]),
    .Z(dac_state_p_main[15])
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:66.13-92.6" *)
  clkgate clkgate (
    .clk_comp(clk_comp),
    .clk_init(clk_init),
    .clk_samp_n(clk_samp_n_raw),
    .clk_samp_p(clk_samp_p_raw),
    .clk_update(clk_update),
    .en_comp(en_comp),
    .en_init(en_init),
    .en_samp_n(en_samp_n),
    .en_samp_p(en_samp_p),
    .en_update(en_update),
    .seq_comp(seq_comp),
    .seq_init(seq_init),
    .seq_samp(seq_samp),
    .seq_update(seq_update)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:95.13-113.6" *)
  salogic salogic_dual (
    .clk_init(clk_init),
    .clk_update(clk_update),
    .comp_n(comp_out_p),
    .comp_p(comp_out_n),
    .dac_astate_n(dac_astate_n),
    .dac_astate_p(dac_astate_p),
    .dac_bstate_n(dac_bstate_n),
    .dac_bstate_p(dac_bstate_p),
    .dac_mode(dac_mode),
    .dac_state_n(dac_state_n_diff),
    .dac_state_p(dac_state_p_diff)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:128.16-136.6" *)
  sampdriver sampdriver_n (
    .clk_in(clk_samp_n_raw),
    .clk_out(clk_samp_n),
    .clk_out_b(clk_samp_n_b)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/adc_digital.v:118.16-126.6" *)
  sampdriver sampdriver_p (
    .clk_in(clk_samp_p_raw),
    .clk_out(clk_samp_p),
    .clk_out_b(clk_samp_p_b)
  );
endmodule

(* keep_hierarchy =  1  *)
(* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:5.1-39.10" *)
(* dont_touch = "true" *)
(* hdlname = "clkgate" *)
module clkgate(seq_init, seq_samp, seq_comp, seq_update, en_init, en_samp_p, en_samp_n, en_comp, en_update, clk_init, clk_samp_p, clk_samp_n, clk_comp, clk_update);
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:7.17-7.25" *)
  input seq_init;
  wire seq_init;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:8.17-8.25" *)
  input seq_samp;
  wire seq_samp;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:9.17-9.25" *)
  input seq_comp;
  wire seq_comp;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:10.17-10.27" *)
  input seq_update;
  wire seq_update;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:13.17-13.24" *)
  input en_init;
  wire en_init;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:14.17-14.26" *)
  input en_samp_p;
  wire en_samp_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:15.17-15.26" *)
  input en_samp_n;
  wire en_samp_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:16.17-16.24" *)
  input en_comp;
  wire en_comp;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:17.17-17.26" *)
  input en_update;
  wire en_update;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:20.17-20.25" *)
  output clk_init;
  wire clk_init;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:21.17-21.27" *)
  output clk_samp_p;
  wire clk_samp_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:22.17-22.27" *)
  output clk_samp_n;
  wire clk_samp_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:23.17-23.25" *)
  output clk_comp;
  wire clk_comp;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/clkgate.v:24.17-24.27" *)
  output clk_update;
  wire clk_update;
  (* hdlname = "clkgate_comp clkgate_cell" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:54.14-54.52" *)
  CKLNQD1LVT \clkgate_comp.clkgate_cell  (
    .CP(seq_comp),
    .E(en_comp),
    .Q(clk_comp)
  );
  (* hdlname = "clkgate_init clkgate_cell" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:54.14-54.52" *)
  CKLNQD1LVT \clkgate_init.clkgate_cell  (
    .CP(seq_init),
    .E(en_init),
    .Q(clk_init)
  );
  (* hdlname = "clkgate_samp_n clkgate_cell" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:54.14-54.52" *)
  CKLNQD1LVT \clkgate_samp_n.clkgate_cell  (
    .CP(seq_samp),
    .E(en_samp_n),
    .Q(clk_samp_n)
  );
  (* hdlname = "clkgate_samp_p clkgate_cell" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:54.14-54.52" *)
  CKLNQD1LVT \clkgate_samp_p.clkgate_cell  (
    .CP(seq_samp),
    .E(en_samp_p),
    .Q(clk_samp_p)
  );
  (* hdlname = "clkgate_update clkgate_cell" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:54.14-54.52" *)
  CKLNQD1LVT \clkgate_update.clkgate_cell  (
    .CP(seq_update),
    .E(en_update),
    .Q(clk_update)
  );
endmodule

(* keep_hierarchy =  1  *)
(* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:12.1-106.10" *)
(* hdlname = "salogic" *)
module salogic(clk_init, clk_update, dac_astate_p, dac_bstate_p, dac_mode, comp_p, dac_astate_n, dac_bstate_n, comp_n, dac_state_p, dac_state_n);
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:14.16-14.24" *)
  input clk_init;
  wire clk_init;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:15.16-15.26" *)
  input clk_update;
  wire clk_update;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:18.23-18.35" *)
  input [15:0] dac_astate_p;
  wire [15:0] dac_astate_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:19.23-19.35" *)
  input [15:0] dac_bstate_p;
  wire [15:0] dac_bstate_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:20.16-20.24" *)
  input dac_mode;
  wire dac_mode;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:21.16-21.22" *)
  input comp_p;
  wire comp_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:24.23-24.35" *)
  input [15:0] dac_astate_n;
  wire [15:0] dac_astate_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:25.23-25.35" *)
  input [15:0] dac_bstate_n;
  wire [15:0] dac_bstate_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:26.16-26.22" *)
  input comp_n;
  wire comp_n;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:29.23-29.34" *)
  output [15:0] dac_state_p;
  wire [15:0] dac_state_p;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:30.23-30.34" *)
  output [15:0] dac_state_n;
  wire [15:0] dac_state_n;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[0] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[10] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[11] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[12] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[13] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[14] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[15] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[1] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[2] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[3] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[4] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[5] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[6] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[7] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[8] ;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:41.12-41.21" *)
  wire \dac_cycle[9] ;
  (* hdlname = "dac_ff[0].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[0].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[0].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[0].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[0].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[0].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[0].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[0].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[0].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[0].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[10].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[10].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[10].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[10].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[10].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[10].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[10].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[10].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[10].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[10].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[11].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[11].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[11].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[11].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[11].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[11].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[11].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[11].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[11].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[11].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[12].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[12].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[12].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[12].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[12].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[12].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[12].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[12].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[12].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[12].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[13].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[13].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[13].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[13].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[13].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[13].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[13].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[13].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[13].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[13].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[14].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[14].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[14].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[14].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[14].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[14].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[14].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[14].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[14].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[14].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[15].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[15].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[15].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[15].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[15].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[15].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[15].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[15].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[15].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[15].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[1].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[1].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[1].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[1].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[1].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[1].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[1].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[1].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[1].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[1].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[2].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[2].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[2].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[2].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[2].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[2].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[2].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[2].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[2].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[2].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[3].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[3].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[3].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[3].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[3].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[3].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[3].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[3].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[3].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[3].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[4].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[4].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[4].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[4].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[4].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[4].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[4].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[4].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[4].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[4].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[5].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[5].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[5].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[5].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[5].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[5].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[5].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[5].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[5].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[5].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[6].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[6].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[6].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[6].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[6].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[6].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[6].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[6].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[6].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[6].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[7].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[7].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[7].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[7].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[7].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[7].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[7].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[7].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[7].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[7].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[8].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[8].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[8].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[8].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[8].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[8].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[8].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[8].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[8].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[8].dac_state_p_ff.Q ;
  (* hdlname = "dac_ff[9].dac_state_n_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[9].dac_state_n_ff.D ;
  (* hdlname = "dac_ff[9].dac_state_n_ff E" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:9.9-9.10" *)
  wire \dac_ff[9].dac_state_n_ff.E ;
  (* hdlname = "dac_ff[9].dac_state_n_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[9].dac_state_n_ff.Q ;
  (* hdlname = "dac_ff[9].dac_state_p_ff D" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:7.9-7.10" *)
  wire \dac_ff[9].dac_state_p_ff.D ;
  (* hdlname = "dac_ff[9].dac_state_p_ff Q" *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:10.10-10.11" *)
  wire \dac_ff[9].dac_state_p_ff.Q ;
  CKND0LVT _174_ (
    .I(\dac_cycle[1] ),
    .ZN(_015_)
  );
  CKBD1LVT _175_ (
    .I(clk_init),
    .Z(_016_)
  );
  NR2D0LVT _176_ (
    .A1(_015_),
    .A2(_016_),
    .ZN(_000_)
  );
  CKND0LVT _177_ (
    .I(\dac_cycle[11] ),
    .ZN(_017_)
  );
  NR2D0LVT _178_ (
    .A1(_017_),
    .A2(_016_),
    .ZN(_001_)
  );
  CKND0LVT _179_ (
    .I(\dac_cycle[12] ),
    .ZN(_018_)
  );
  NR2D0LVT _180_ (
    .A1(_018_),
    .A2(_016_),
    .ZN(_002_)
  );
  CKND0LVT _181_ (
    .I(\dac_cycle[13] ),
    .ZN(_019_)
  );
  NR2D0LVT _182_ (
    .A1(_019_),
    .A2(_016_),
    .ZN(_003_)
  );
  CKND0LVT _183_ (
    .I(\dac_cycle[14] ),
    .ZN(_020_)
  );
  NR2D0LVT _184_ (
    .A1(_020_),
    .A2(_016_),
    .ZN(_004_)
  );
  CKND0LVT _185_ (
    .I(\dac_cycle[15] ),
    .ZN(_021_)
  );
  NR2D0LVT _186_ (
    .A1(_021_),
    .A2(_016_),
    .ZN(_005_)
  );
  CKND0LVT _187_ (
    .I(\dac_cycle[2] ),
    .ZN(_022_)
  );
  NR2D0LVT _188_ (
    .A1(_022_),
    .A2(_016_),
    .ZN(_006_)
  );
  CKND0LVT _189_ (
    .I(\dac_cycle[3] ),
    .ZN(_023_)
  );
  NR2D0LVT _190_ (
    .A1(_023_),
    .A2(_016_),
    .ZN(_007_)
  );
  CKND0LVT _191_ (
    .I(\dac_cycle[4] ),
    .ZN(_024_)
  );
  NR2D0LVT _192_ (
    .A1(_024_),
    .A2(_016_),
    .ZN(_008_)
  );
  CKND0LVT _193_ (
    .I(\dac_cycle[5] ),
    .ZN(_025_)
  );
  NR2D0LVT _194_ (
    .A1(_025_),
    .A2(_016_),
    .ZN(_009_)
  );
  CKND0LVT _195_ (
    .I(\dac_cycle[6] ),
    .ZN(_026_)
  );
  NR2D0LVT _196_ (
    .A1(_026_),
    .A2(clk_init),
    .ZN(_010_)
  );
  CKND0LVT _197_ (
    .I(\dac_cycle[7] ),
    .ZN(_027_)
  );
  NR2D0LVT _198_ (
    .A1(_027_),
    .A2(clk_init),
    .ZN(_011_)
  );
  CKND0LVT _199_ (
    .I(\dac_cycle[8] ),
    .ZN(_028_)
  );
  NR2D0LVT _200_ (
    .A1(_028_),
    .A2(clk_init),
    .ZN(_012_)
  );
  CKND0LVT _201_ (
    .I(\dac_cycle[9] ),
    .ZN(_029_)
  );
  NR2D0LVT _202_ (
    .A1(_029_),
    .A2(clk_init),
    .ZN(_013_)
  );
  CKND0LVT _203_ (
    .I(\dac_cycle[10] ),
    .ZN(_030_)
  );
  NR2D0LVT _204_ (
    .A1(_030_),
    .A2(clk_init),
    .ZN(_014_)
  );
  CKND2D0LVT _205_ (
    .A1(dac_mode),
    .A2(comp_n),
    .ZN(_031_)
  );
  INVD2LVT _206_ (
    .I(clk_init),
    .ZN(_032_)
  );
  ND2D2LVT _207_ (
    .A1(_031_),
    .A2(_032_),
    .ZN(_033_)
  );
  BUFFD2LVT _208_ (
    .I(_033_),
    .Z(_034_)
  );
  CKND0LVT _209_ (
    .I(dac_bstate_n[0]),
    .ZN(_035_)
  );
  CKBD1LVT _210_ (
    .I(dac_mode),
    .Z(_036_)
  );
  NR2D0LVT _211_ (
    .A1(_035_),
    .A2(_036_),
    .ZN(_037_)
  );
  NR2D1LVT _212_ (
    .A1(_034_),
    .A2(_037_),
    .ZN(_038_)
  );
  CKBD1LVT _213_ (
    .I(_032_),
    .Z(_039_)
  );
  NR2D0LVT _214_ (
    .A1(_039_),
    .A2(dac_astate_n[0]),
    .ZN(_040_)
  );
  NR2D1LVT _215_ (
    .A1(_038_),
    .A2(_040_),
    .ZN(\dac_ff[0].dac_state_n_ff.D )
  );
  INR2D2LVT _216_ (
    .A1(dac_mode),
    .B1(clk_init),
    .ZN(_041_)
  );
  CKBD1LVT _217_ (
    .I(_041_),
    .Z(_042_)
  );
  IND2D0LVT _218_ (
    .A1(\dac_cycle[0] ),
    .B1(_042_),
    .ZN(\dac_ff[0].dac_state_n_ff.E )
  );
  CKND2D0LVT _219_ (
    .A1(comp_p),
    .A2(dac_mode),
    .ZN(_043_)
  );
  ND2D2LVT _220_ (
    .A1(_043_),
    .A2(_032_),
    .ZN(_044_)
  );
  BUFFD2LVT _221_ (
    .I(_044_),
    .Z(_045_)
  );
  CKND0LVT _222_ (
    .I(dac_bstate_p[0]),
    .ZN(_046_)
  );
  NR2D0LVT _223_ (
    .A1(_046_),
    .A2(_036_),
    .ZN(_047_)
  );
  NR2D1LVT _224_ (
    .A1(_045_),
    .A2(_047_),
    .ZN(_048_)
  );
  NR2D0LVT _225_ (
    .A1(_039_),
    .A2(dac_astate_p[0]),
    .ZN(_049_)
  );
  NR2D1LVT _226_ (
    .A1(_048_),
    .A2(_049_),
    .ZN(\dac_ff[0].dac_state_p_ff.D )
  );
  CKND0LVT _227_ (
    .I(dac_bstate_n[10]),
    .ZN(_050_)
  );
  NR2D0LVT _228_ (
    .A1(_050_),
    .A2(_036_),
    .ZN(_051_)
  );
  NR2D1LVT _229_ (
    .A1(_034_),
    .A2(_051_),
    .ZN(_052_)
  );
  NR2D0LVT _230_ (
    .A1(_039_),
    .A2(dac_astate_n[10]),
    .ZN(_053_)
  );
  NR2D1LVT _231_ (
    .A1(_052_),
    .A2(_053_),
    .ZN(\dac_ff[10].dac_state_n_ff.D )
  );
  CKND2D0LVT _232_ (
    .A1(_042_),
    .A2(_030_),
    .ZN(\dac_ff[10].dac_state_n_ff.E )
  );
  CKND0LVT _233_ (
    .I(dac_bstate_p[10]),
    .ZN(_054_)
  );
  NR2D0LVT _234_ (
    .A1(_054_),
    .A2(_036_),
    .ZN(_055_)
  );
  NR2D1LVT _235_ (
    .A1(_045_),
    .A2(_055_),
    .ZN(_056_)
  );
  NR2D0LVT _236_ (
    .A1(_039_),
    .A2(dac_astate_p[10]),
    .ZN(_057_)
  );
  NR2D1LVT _237_ (
    .A1(_056_),
    .A2(_057_),
    .ZN(\dac_ff[10].dac_state_p_ff.D )
  );
  CKND0LVT _238_ (
    .I(dac_bstate_n[11]),
    .ZN(_058_)
  );
  NR2D0LVT _239_ (
    .A1(_058_),
    .A2(_036_),
    .ZN(_059_)
  );
  NR2D1LVT _240_ (
    .A1(_034_),
    .A2(_059_),
    .ZN(_060_)
  );
  NR2D0LVT _241_ (
    .A1(_039_),
    .A2(dac_astate_n[11]),
    .ZN(_061_)
  );
  NR2D1LVT _242_ (
    .A1(_060_),
    .A2(_061_),
    .ZN(\dac_ff[11].dac_state_n_ff.D )
  );
  CKND2D0LVT _243_ (
    .A1(_042_),
    .A2(_017_),
    .ZN(\dac_ff[11].dac_state_n_ff.E )
  );
  CKND0LVT _244_ (
    .I(dac_bstate_p[11]),
    .ZN(_062_)
  );
  NR2D0LVT _245_ (
    .A1(_062_),
    .A2(_036_),
    .ZN(_063_)
  );
  NR2D1LVT _246_ (
    .A1(_045_),
    .A2(_063_),
    .ZN(_064_)
  );
  NR2D0LVT _247_ (
    .A1(_039_),
    .A2(dac_astate_p[11]),
    .ZN(_065_)
  );
  NR2D1LVT _248_ (
    .A1(_064_),
    .A2(_065_),
    .ZN(\dac_ff[11].dac_state_p_ff.D )
  );
  CKND0LVT _249_ (
    .I(dac_bstate_n[12]),
    .ZN(_066_)
  );
  NR2D0LVT _250_ (
    .A1(_066_),
    .A2(_036_),
    .ZN(_067_)
  );
  NR2D1LVT _251_ (
    .A1(_034_),
    .A2(_067_),
    .ZN(_068_)
  );
  NR2D0LVT _252_ (
    .A1(_039_),
    .A2(dac_astate_n[12]),
    .ZN(_069_)
  );
  NR2D1LVT _253_ (
    .A1(_068_),
    .A2(_069_),
    .ZN(\dac_ff[12].dac_state_n_ff.D )
  );
  CKND2D0LVT _254_ (
    .A1(_042_),
    .A2(_018_),
    .ZN(\dac_ff[12].dac_state_n_ff.E )
  );
  CKND0LVT _255_ (
    .I(dac_bstate_p[12]),
    .ZN(_070_)
  );
  NR2D0LVT _256_ (
    .A1(_070_),
    .A2(_036_),
    .ZN(_071_)
  );
  NR2D1LVT _257_ (
    .A1(_045_),
    .A2(_071_),
    .ZN(_072_)
  );
  NR2D0LVT _258_ (
    .A1(_039_),
    .A2(dac_astate_p[12]),
    .ZN(_073_)
  );
  NR2D1LVT _259_ (
    .A1(_072_),
    .A2(_073_),
    .ZN(\dac_ff[12].dac_state_p_ff.D )
  );
  CKND0LVT _260_ (
    .I(dac_bstate_n[13]),
    .ZN(_074_)
  );
  NR2D0LVT _261_ (
    .A1(_074_),
    .A2(_036_),
    .ZN(_075_)
  );
  NR2D1LVT _262_ (
    .A1(_034_),
    .A2(_075_),
    .ZN(_076_)
  );
  NR2D0LVT _263_ (
    .A1(_039_),
    .A2(dac_astate_n[13]),
    .ZN(_077_)
  );
  NR2D1LVT _264_ (
    .A1(_076_),
    .A2(_077_),
    .ZN(\dac_ff[13].dac_state_n_ff.D )
  );
  CKND2D0LVT _265_ (
    .A1(_042_),
    .A2(_019_),
    .ZN(\dac_ff[13].dac_state_n_ff.E )
  );
  CKND0LVT _266_ (
    .I(dac_bstate_p[13]),
    .ZN(_078_)
  );
  NR2D0LVT _267_ (
    .A1(_078_),
    .A2(_036_),
    .ZN(_079_)
  );
  NR2D1LVT _268_ (
    .A1(_045_),
    .A2(_079_),
    .ZN(_080_)
  );
  NR2D0LVT _269_ (
    .A1(_039_),
    .A2(dac_astate_p[13]),
    .ZN(_081_)
  );
  NR2D1LVT _270_ (
    .A1(_080_),
    .A2(_081_),
    .ZN(\dac_ff[13].dac_state_p_ff.D )
  );
  CKND0LVT _271_ (
    .I(dac_bstate_n[14]),
    .ZN(_082_)
  );
  CKBD1LVT _272_ (
    .I(dac_mode),
    .Z(_083_)
  );
  NR2D0LVT _273_ (
    .A1(_082_),
    .A2(_083_),
    .ZN(_084_)
  );
  NR2D1LVT _274_ (
    .A1(_034_),
    .A2(_084_),
    .ZN(_085_)
  );
  CKBD1LVT _275_ (
    .I(_032_),
    .Z(_086_)
  );
  NR2XD0LVT _276_ (
    .A1(_086_),
    .A2(dac_astate_n[14]),
    .ZN(_087_)
  );
  NR2D1LVT _277_ (
    .A1(_085_),
    .A2(_087_),
    .ZN(\dac_ff[14].dac_state_n_ff.D )
  );
  CKND2D0LVT _278_ (
    .A1(_042_),
    .A2(_020_),
    .ZN(\dac_ff[14].dac_state_n_ff.E )
  );
  CKND0LVT _279_ (
    .I(dac_bstate_p[14]),
    .ZN(_088_)
  );
  NR2D0LVT _280_ (
    .A1(_088_),
    .A2(_083_),
    .ZN(_089_)
  );
  NR2D1LVT _281_ (
    .A1(_045_),
    .A2(_089_),
    .ZN(_090_)
  );
  NR2XD0LVT _282_ (
    .A1(_086_),
    .A2(dac_astate_p[14]),
    .ZN(_091_)
  );
  NR2D1LVT _283_ (
    .A1(_090_),
    .A2(_091_),
    .ZN(\dac_ff[14].dac_state_p_ff.D )
  );
  CKND0LVT _284_ (
    .I(dac_bstate_n[15]),
    .ZN(_092_)
  );
  NR2D0LVT _285_ (
    .A1(_092_),
    .A2(_083_),
    .ZN(_093_)
  );
  NR2D1LVT _286_ (
    .A1(_034_),
    .A2(_093_),
    .ZN(_094_)
  );
  NR2XD0LVT _287_ (
    .A1(_086_),
    .A2(dac_astate_n[15]),
    .ZN(_095_)
  );
  NR2D1LVT _288_ (
    .A1(_094_),
    .A2(_095_),
    .ZN(\dac_ff[15].dac_state_n_ff.D )
  );
  CKND2D0LVT _289_ (
    .A1(_042_),
    .A2(_021_),
    .ZN(\dac_ff[15].dac_state_n_ff.E )
  );
  CKND0LVT _290_ (
    .I(dac_bstate_p[15]),
    .ZN(_096_)
  );
  NR2D0LVT _291_ (
    .A1(_096_),
    .A2(_083_),
    .ZN(_097_)
  );
  NR2D1LVT _292_ (
    .A1(_045_),
    .A2(_097_),
    .ZN(_098_)
  );
  NR2XD0LVT _293_ (
    .A1(_086_),
    .A2(dac_astate_p[15]),
    .ZN(_099_)
  );
  NR2D1LVT _294_ (
    .A1(_098_),
    .A2(_099_),
    .ZN(\dac_ff[15].dac_state_p_ff.D )
  );
  CKND0LVT _295_ (
    .I(dac_bstate_n[1]),
    .ZN(_100_)
  );
  NR2D0LVT _296_ (
    .A1(_100_),
    .A2(_083_),
    .ZN(_101_)
  );
  NR2D1LVT _297_ (
    .A1(_034_),
    .A2(_101_),
    .ZN(_102_)
  );
  NR2XD0LVT _298_ (
    .A1(_086_),
    .A2(dac_astate_n[1]),
    .ZN(_103_)
  );
  NR2D1LVT _299_ (
    .A1(_102_),
    .A2(_103_),
    .ZN(\dac_ff[1].dac_state_n_ff.D )
  );
  CKND2D0LVT _300_ (
    .A1(_042_),
    .A2(_015_),
    .ZN(\dac_ff[1].dac_state_n_ff.E )
  );
  CKND0LVT _301_ (
    .I(dac_bstate_p[1]),
    .ZN(_104_)
  );
  NR2D0LVT _302_ (
    .A1(_104_),
    .A2(_083_),
    .ZN(_105_)
  );
  NR2D1LVT _303_ (
    .A1(_045_),
    .A2(_105_),
    .ZN(_106_)
  );
  NR2XD0LVT _304_ (
    .A1(_086_),
    .A2(dac_astate_p[1]),
    .ZN(_107_)
  );
  NR2D1LVT _305_ (
    .A1(_106_),
    .A2(_107_),
    .ZN(\dac_ff[1].dac_state_p_ff.D )
  );
  CKND0LVT _306_ (
    .I(dac_bstate_n[2]),
    .ZN(_108_)
  );
  NR2D0LVT _307_ (
    .A1(_108_),
    .A2(_083_),
    .ZN(_109_)
  );
  NR2D1LVT _308_ (
    .A1(_034_),
    .A2(_109_),
    .ZN(_110_)
  );
  NR2XD0LVT _309_ (
    .A1(_086_),
    .A2(dac_astate_n[2]),
    .ZN(_111_)
  );
  NR2D1LVT _310_ (
    .A1(_110_),
    .A2(_111_),
    .ZN(\dac_ff[2].dac_state_n_ff.D )
  );
  CKND2D0LVT _311_ (
    .A1(_042_),
    .A2(_022_),
    .ZN(\dac_ff[2].dac_state_n_ff.E )
  );
  CKND0LVT _312_ (
    .I(dac_bstate_p[2]),
    .ZN(_112_)
  );
  NR2D0LVT _313_ (
    .A1(_112_),
    .A2(_083_),
    .ZN(_113_)
  );
  NR2D1LVT _314_ (
    .A1(_045_),
    .A2(_113_),
    .ZN(_114_)
  );
  NR2XD0LVT _315_ (
    .A1(_086_),
    .A2(dac_astate_p[2]),
    .ZN(_115_)
  );
  NR2D1LVT _316_ (
    .A1(_114_),
    .A2(_115_),
    .ZN(\dac_ff[2].dac_state_p_ff.D )
  );
  CKND0LVT _317_ (
    .I(dac_bstate_n[3]),
    .ZN(_116_)
  );
  NR2D0LVT _318_ (
    .A1(_116_),
    .A2(_083_),
    .ZN(_117_)
  );
  NR2D1LVT _319_ (
    .A1(_034_),
    .A2(_117_),
    .ZN(_118_)
  );
  NR2XD0LVT _320_ (
    .A1(_086_),
    .A2(dac_astate_n[3]),
    .ZN(_119_)
  );
  NR2D1LVT _321_ (
    .A1(_118_),
    .A2(_119_),
    .ZN(\dac_ff[3].dac_state_n_ff.D )
  );
  CKND2D0LVT _322_ (
    .A1(_042_),
    .A2(_023_),
    .ZN(\dac_ff[3].dac_state_n_ff.E )
  );
  CKND0LVT _323_ (
    .I(dac_bstate_p[3]),
    .ZN(_120_)
  );
  NR2D0LVT _324_ (
    .A1(_120_),
    .A2(_083_),
    .ZN(_121_)
  );
  NR2D1LVT _325_ (
    .A1(_045_),
    .A2(_121_),
    .ZN(_122_)
  );
  NR2XD0LVT _326_ (
    .A1(_086_),
    .A2(dac_astate_p[3]),
    .ZN(_123_)
  );
  NR2D1LVT _327_ (
    .A1(_122_),
    .A2(_123_),
    .ZN(\dac_ff[3].dac_state_p_ff.D )
  );
  CKND0LVT _328_ (
    .I(dac_bstate_n[4]),
    .ZN(_124_)
  );
  CKBD1LVT _329_ (
    .I(dac_mode),
    .Z(_125_)
  );
  NR2D0LVT _330_ (
    .A1(_124_),
    .A2(_125_),
    .ZN(_126_)
  );
  NR2D0LVT _331_ (
    .A1(_033_),
    .A2(_126_),
    .ZN(_127_)
  );
  BUFFD2LVT _332_ (
    .I(_032_),
    .Z(_128_)
  );
  NR2D0LVT _333_ (
    .A1(_128_),
    .A2(dac_astate_n[4]),
    .ZN(_129_)
  );
  NR2D0LVT _334_ (
    .A1(_127_),
    .A2(_129_),
    .ZN(\dac_ff[4].dac_state_n_ff.D )
  );
  CKND2D0LVT _335_ (
    .A1(_041_),
    .A2(_024_),
    .ZN(\dac_ff[4].dac_state_n_ff.E )
  );
  CKND0LVT _336_ (
    .I(dac_bstate_p[4]),
    .ZN(_130_)
  );
  NR2D0LVT _337_ (
    .A1(_130_),
    .A2(_125_),
    .ZN(_131_)
  );
  NR2D0LVT _338_ (
    .A1(_044_),
    .A2(_131_),
    .ZN(_132_)
  );
  NR2D0LVT _339_ (
    .A1(_128_),
    .A2(dac_astate_p[4]),
    .ZN(_133_)
  );
  NR2D0LVT _340_ (
    .A1(_132_),
    .A2(_133_),
    .ZN(\dac_ff[4].dac_state_p_ff.D )
  );
  CKND0LVT _341_ (
    .I(dac_bstate_n[5]),
    .ZN(_134_)
  );
  NR2D0LVT _342_ (
    .A1(_134_),
    .A2(_125_),
    .ZN(_135_)
  );
  NR2D0LVT _343_ (
    .A1(_033_),
    .A2(_135_),
    .ZN(_136_)
  );
  NR2D0LVT _344_ (
    .A1(_128_),
    .A2(dac_astate_n[5]),
    .ZN(_137_)
  );
  NR2D0LVT _345_ (
    .A1(_136_),
    .A2(_137_),
    .ZN(\dac_ff[5].dac_state_n_ff.D )
  );
  CKND2D0LVT _346_ (
    .A1(_041_),
    .A2(_025_),
    .ZN(\dac_ff[5].dac_state_n_ff.E )
  );
  CKND0LVT _347_ (
    .I(dac_bstate_p[5]),
    .ZN(_138_)
  );
  NR2D0LVT _348_ (
    .A1(_138_),
    .A2(_125_),
    .ZN(_139_)
  );
  NR2D0LVT _349_ (
    .A1(_044_),
    .A2(_139_),
    .ZN(_140_)
  );
  NR2D0LVT _350_ (
    .A1(_128_),
    .A2(dac_astate_p[5]),
    .ZN(_141_)
  );
  NR2D0LVT _351_ (
    .A1(_140_),
    .A2(_141_),
    .ZN(\dac_ff[5].dac_state_p_ff.D )
  );
  CKND0LVT _352_ (
    .I(dac_bstate_n[6]),
    .ZN(_142_)
  );
  NR2D0LVT _353_ (
    .A1(_142_),
    .A2(_125_),
    .ZN(_143_)
  );
  NR2D0LVT _354_ (
    .A1(_033_),
    .A2(_143_),
    .ZN(_144_)
  );
  NR2D0LVT _355_ (
    .A1(_128_),
    .A2(dac_astate_n[6]),
    .ZN(_145_)
  );
  NR2D0LVT _356_ (
    .A1(_144_),
    .A2(_145_),
    .ZN(\dac_ff[6].dac_state_n_ff.D )
  );
  CKND2D0LVT _357_ (
    .A1(_041_),
    .A2(_026_),
    .ZN(\dac_ff[6].dac_state_n_ff.E )
  );
  CKND0LVT _358_ (
    .I(dac_bstate_p[6]),
    .ZN(_146_)
  );
  NR2D0LVT _359_ (
    .A1(_146_),
    .A2(_125_),
    .ZN(_147_)
  );
  NR2D0LVT _360_ (
    .A1(_044_),
    .A2(_147_),
    .ZN(_148_)
  );
  NR2D0LVT _361_ (
    .A1(_128_),
    .A2(dac_astate_p[6]),
    .ZN(_149_)
  );
  NR2D0LVT _362_ (
    .A1(_148_),
    .A2(_149_),
    .ZN(\dac_ff[6].dac_state_p_ff.D )
  );
  CKND0LVT _363_ (
    .I(dac_bstate_n[7]),
    .ZN(_150_)
  );
  NR2D0LVT _364_ (
    .A1(_150_),
    .A2(_125_),
    .ZN(_151_)
  );
  NR2D0LVT _365_ (
    .A1(_033_),
    .A2(_151_),
    .ZN(_152_)
  );
  NR2D0LVT _366_ (
    .A1(_128_),
    .A2(dac_astate_n[7]),
    .ZN(_153_)
  );
  NR2D0LVT _367_ (
    .A1(_152_),
    .A2(_153_),
    .ZN(\dac_ff[7].dac_state_n_ff.D )
  );
  CKND2D0LVT _368_ (
    .A1(_041_),
    .A2(_027_),
    .ZN(\dac_ff[7].dac_state_n_ff.E )
  );
  CKND0LVT _369_ (
    .I(dac_bstate_p[7]),
    .ZN(_154_)
  );
  NR2D0LVT _370_ (
    .A1(_154_),
    .A2(_125_),
    .ZN(_155_)
  );
  NR2D0LVT _371_ (
    .A1(_044_),
    .A2(_155_),
    .ZN(_156_)
  );
  NR2D0LVT _372_ (
    .A1(_128_),
    .A2(dac_astate_p[7]),
    .ZN(_157_)
  );
  NR2D0LVT _373_ (
    .A1(_156_),
    .A2(_157_),
    .ZN(\dac_ff[7].dac_state_p_ff.D )
  );
  CKND0LVT _374_ (
    .I(dac_bstate_n[8]),
    .ZN(_158_)
  );
  NR2D0LVT _375_ (
    .A1(_158_),
    .A2(_125_),
    .ZN(_159_)
  );
  NR2D0LVT _376_ (
    .A1(_033_),
    .A2(_159_),
    .ZN(_160_)
  );
  NR2D0LVT _377_ (
    .A1(_128_),
    .A2(dac_astate_n[8]),
    .ZN(_161_)
  );
  NR2D0LVT _378_ (
    .A1(_160_),
    .A2(_161_),
    .ZN(\dac_ff[8].dac_state_n_ff.D )
  );
  CKND2D0LVT _379_ (
    .A1(_041_),
    .A2(_028_),
    .ZN(\dac_ff[8].dac_state_n_ff.E )
  );
  CKND0LVT _380_ (
    .I(dac_bstate_p[8]),
    .ZN(_162_)
  );
  NR2D0LVT _381_ (
    .A1(_162_),
    .A2(_125_),
    .ZN(_163_)
  );
  NR2D0LVT _382_ (
    .A1(_044_),
    .A2(_163_),
    .ZN(_164_)
  );
  NR2D0LVT _383_ (
    .A1(_128_),
    .A2(dac_astate_p[8]),
    .ZN(_165_)
  );
  NR2D0LVT _384_ (
    .A1(_164_),
    .A2(_165_),
    .ZN(\dac_ff[8].dac_state_p_ff.D )
  );
  CKND0LVT _385_ (
    .I(dac_bstate_n[9]),
    .ZN(_166_)
  );
  NR2D0LVT _386_ (
    .A1(_166_),
    .A2(dac_mode),
    .ZN(_167_)
  );
  NR2D0LVT _387_ (
    .A1(_033_),
    .A2(_167_),
    .ZN(_168_)
  );
  NR2D0LVT _388_ (
    .A1(_032_),
    .A2(dac_astate_n[9]),
    .ZN(_169_)
  );
  NR2D0LVT _389_ (
    .A1(_168_),
    .A2(_169_),
    .ZN(\dac_ff[9].dac_state_n_ff.D )
  );
  CKND2D0LVT _390_ (
    .A1(_041_),
    .A2(_029_),
    .ZN(\dac_ff[9].dac_state_n_ff.E )
  );
  CKND0LVT _391_ (
    .I(dac_bstate_p[9]),
    .ZN(_170_)
  );
  NR2D0LVT _392_ (
    .A1(_170_),
    .A2(dac_mode),
    .ZN(_171_)
  );
  NR2D0LVT _393_ (
    .A1(_044_),
    .A2(_171_),
    .ZN(_172_)
  );
  NR2D0LVT _394_ (
    .A1(_032_),
    .A2(dac_astate_p[9]),
    .ZN(_173_)
  );
  NR2D0LVT _395_ (
    .A1(_172_),
    .A2(_173_),
    .ZN(\dac_ff[9].dac_state_p_ff.D )
  );
  BUFFD0LVT _396_ (
    .I(\dac_ff[0].dac_state_n_ff.Q ),
    .Z(dac_state_n[0])
  );
  BUFFD0LVT _397_ (
    .I(\dac_ff[1].dac_state_n_ff.Q ),
    .Z(dac_state_n[1])
  );
  BUFFD0LVT _398_ (
    .I(\dac_ff[2].dac_state_n_ff.Q ),
    .Z(dac_state_n[2])
  );
  BUFFD0LVT _399_ (
    .I(\dac_ff[3].dac_state_n_ff.Q ),
    .Z(dac_state_n[3])
  );
  BUFFD0LVT _400_ (
    .I(\dac_ff[4].dac_state_n_ff.Q ),
    .Z(dac_state_n[4])
  );
  BUFFD0LVT _401_ (
    .I(\dac_ff[5].dac_state_n_ff.Q ),
    .Z(dac_state_n[5])
  );
  BUFFD0LVT _402_ (
    .I(\dac_ff[6].dac_state_n_ff.Q ),
    .Z(dac_state_n[6])
  );
  BUFFD0LVT _403_ (
    .I(\dac_ff[7].dac_state_n_ff.Q ),
    .Z(dac_state_n[7])
  );
  BUFFD0LVT _404_ (
    .I(\dac_ff[8].dac_state_n_ff.Q ),
    .Z(dac_state_n[8])
  );
  BUFFD0LVT _405_ (
    .I(\dac_ff[9].dac_state_n_ff.Q ),
    .Z(dac_state_n[9])
  );
  BUFFD0LVT _406_ (
    .I(\dac_ff[10].dac_state_n_ff.Q ),
    .Z(dac_state_n[10])
  );
  BUFFD0LVT _407_ (
    .I(\dac_ff[11].dac_state_n_ff.Q ),
    .Z(dac_state_n[11])
  );
  BUFFD0LVT _408_ (
    .I(\dac_ff[12].dac_state_n_ff.Q ),
    .Z(dac_state_n[12])
  );
  BUFFD0LVT _409_ (
    .I(\dac_ff[13].dac_state_n_ff.Q ),
    .Z(dac_state_n[13])
  );
  BUFFD0LVT _410_ (
    .I(\dac_ff[14].dac_state_n_ff.Q ),
    .Z(dac_state_n[14])
  );
  BUFFD0LVT _411_ (
    .I(\dac_ff[15].dac_state_n_ff.Q ),
    .Z(dac_state_n[15])
  );
  BUFFD0LVT _412_ (
    .I(\dac_ff[0].dac_state_p_ff.Q ),
    .Z(dac_state_p[0])
  );
  BUFFD0LVT _413_ (
    .I(\dac_ff[1].dac_state_p_ff.Q ),
    .Z(dac_state_p[1])
  );
  BUFFD0LVT _414_ (
    .I(\dac_ff[2].dac_state_p_ff.Q ),
    .Z(dac_state_p[2])
  );
  BUFFD0LVT _415_ (
    .I(\dac_ff[3].dac_state_p_ff.Q ),
    .Z(dac_state_p[3])
  );
  BUFFD0LVT _416_ (
    .I(\dac_ff[4].dac_state_p_ff.Q ),
    .Z(dac_state_p[4])
  );
  BUFFD0LVT _417_ (
    .I(\dac_ff[5].dac_state_p_ff.Q ),
    .Z(dac_state_p[5])
  );
  BUFFD0LVT _418_ (
    .I(\dac_ff[6].dac_state_p_ff.Q ),
    .Z(dac_state_p[6])
  );
  BUFFD0LVT _419_ (
    .I(\dac_ff[7].dac_state_p_ff.Q ),
    .Z(dac_state_p[7])
  );
  BUFFD0LVT _420_ (
    .I(\dac_ff[8].dac_state_p_ff.Q ),
    .Z(dac_state_p[8])
  );
  BUFFD0LVT _421_ (
    .I(\dac_ff[9].dac_state_p_ff.Q ),
    .Z(dac_state_p[9])
  );
  BUFFD0LVT _422_ (
    .I(\dac_ff[10].dac_state_p_ff.Q ),
    .Z(dac_state_p[10])
  );
  BUFFD0LVT _423_ (
    .I(\dac_ff[11].dac_state_p_ff.Q ),
    .Z(dac_state_p[11])
  );
  BUFFD0LVT _424_ (
    .I(\dac_ff[12].dac_state_p_ff.Q ),
    .Z(dac_state_p[12])
  );
  BUFFD0LVT _425_ (
    .I(\dac_ff[13].dac_state_p_ff.Q ),
    .Z(dac_state_p[13])
  );
  BUFFD0LVT _426_ (
    .I(\dac_ff[14].dac_state_p_ff.Q ),
    .Z(dac_state_p[14])
  );
  BUFFD0LVT _427_ (
    .I(\dac_ff[15].dac_state_p_ff.Q ),
    .Z(dac_state_p[15])
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[0]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_000_),
    .Q(\dac_cycle[0] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[10]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_001_),
    .Q(\dac_cycle[10] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[11]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_002_),
    .Q(\dac_cycle[11] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[12]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_003_),
    .Q(\dac_cycle[12] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[13]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_004_),
    .Q(\dac_cycle[13] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[14]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_005_),
    .Q(\dac_cycle[14] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[15]$_DFF_P_  (
    .CP(clk_update),
    .D(clk_init),
    .Q(\dac_cycle[15] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[1]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_006_),
    .Q(\dac_cycle[1] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[2]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_007_),
    .Q(\dac_cycle[2] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[3]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_008_),
    .Q(\dac_cycle[3] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[4]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_009_),
    .Q(\dac_cycle[4] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[5]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_010_),
    .Q(\dac_cycle[5] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[6]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_011_),
    .Q(\dac_cycle[6] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[7]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_012_),
    .Q(\dac_cycle[7] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[8]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_013_),
    .Q(\dac_cycle[8] )
  );
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/salogic.v:96.1-103.4" *)
  DFQD1LVT \dac_cycle[9]$_SDFF_PP0_  (
    .CP(clk_update),
    .D(_014_),
    .Q(\dac_cycle[9] )
  );
  (* hdlname = "dac_ff[0].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[0].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[0].dac_state_n_ff.D ),
    .E(\dac_ff[0].dac_state_n_ff.E ),
    .Q(\dac_ff[0].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[0].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[0].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[0].dac_state_p_ff.D ),
    .E(\dac_ff[0].dac_state_n_ff.E ),
    .Q(\dac_ff[0].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[10].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[10].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[10].dac_state_n_ff.D ),
    .E(\dac_ff[10].dac_state_n_ff.E ),
    .Q(\dac_ff[10].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[10].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[10].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[10].dac_state_p_ff.D ),
    .E(\dac_ff[10].dac_state_n_ff.E ),
    .Q(\dac_ff[10].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[11].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[11].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[11].dac_state_n_ff.D ),
    .E(\dac_ff[11].dac_state_n_ff.E ),
    .Q(\dac_ff[11].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[11].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[11].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[11].dac_state_p_ff.D ),
    .E(\dac_ff[11].dac_state_n_ff.E ),
    .Q(\dac_ff[11].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[12].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[12].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[12].dac_state_n_ff.D ),
    .E(\dac_ff[12].dac_state_n_ff.E ),
    .Q(\dac_ff[12].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[12].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[12].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[12].dac_state_p_ff.D ),
    .E(\dac_ff[12].dac_state_n_ff.E ),
    .Q(\dac_ff[12].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[13].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[13].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[13].dac_state_n_ff.D ),
    .E(\dac_ff[13].dac_state_n_ff.E ),
    .Q(\dac_ff[13].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[13].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[13].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[13].dac_state_p_ff.D ),
    .E(\dac_ff[13].dac_state_n_ff.E ),
    .Q(\dac_ff[13].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[14].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[14].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[14].dac_state_n_ff.D ),
    .E(\dac_ff[14].dac_state_n_ff.E ),
    .Q(\dac_ff[14].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[14].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[14].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[14].dac_state_p_ff.D ),
    .E(\dac_ff[14].dac_state_n_ff.E ),
    .Q(\dac_ff[14].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[15].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[15].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[15].dac_state_n_ff.D ),
    .E(\dac_ff[15].dac_state_n_ff.E ),
    .Q(\dac_ff[15].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[15].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[15].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[15].dac_state_p_ff.D ),
    .E(\dac_ff[15].dac_state_n_ff.E ),
    .Q(\dac_ff[15].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[1].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[1].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[1].dac_state_n_ff.D ),
    .E(\dac_ff[1].dac_state_n_ff.E ),
    .Q(\dac_ff[1].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[1].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[1].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[1].dac_state_p_ff.D ),
    .E(\dac_ff[1].dac_state_n_ff.E ),
    .Q(\dac_ff[1].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[2].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[2].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[2].dac_state_n_ff.D ),
    .E(\dac_ff[2].dac_state_n_ff.E ),
    .Q(\dac_ff[2].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[2].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[2].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[2].dac_state_p_ff.D ),
    .E(\dac_ff[2].dac_state_n_ff.E ),
    .Q(\dac_ff[2].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[3].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[3].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[3].dac_state_n_ff.D ),
    .E(\dac_ff[3].dac_state_n_ff.E ),
    .Q(\dac_ff[3].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[3].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[3].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[3].dac_state_p_ff.D ),
    .E(\dac_ff[3].dac_state_n_ff.E ),
    .Q(\dac_ff[3].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[4].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[4].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[4].dac_state_n_ff.D ),
    .E(\dac_ff[4].dac_state_n_ff.E ),
    .Q(\dac_ff[4].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[4].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[4].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[4].dac_state_p_ff.D ),
    .E(\dac_ff[4].dac_state_n_ff.E ),
    .Q(\dac_ff[4].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[5].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[5].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[5].dac_state_n_ff.D ),
    .E(\dac_ff[5].dac_state_n_ff.E ),
    .Q(\dac_ff[5].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[5].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[5].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[5].dac_state_p_ff.D ),
    .E(\dac_ff[5].dac_state_n_ff.E ),
    .Q(\dac_ff[5].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[6].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[6].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[6].dac_state_n_ff.D ),
    .E(\dac_ff[6].dac_state_n_ff.E ),
    .Q(\dac_ff[6].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[6].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[6].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[6].dac_state_p_ff.D ),
    .E(\dac_ff[6].dac_state_n_ff.E ),
    .Q(\dac_ff[6].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[7].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[7].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[7].dac_state_n_ff.D ),
    .E(\dac_ff[7].dac_state_n_ff.E ),
    .Q(\dac_ff[7].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[7].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[7].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[7].dac_state_p_ff.D ),
    .E(\dac_ff[7].dac_state_n_ff.E ),
    .Q(\dac_ff[7].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[8].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[8].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[8].dac_state_n_ff.D ),
    .E(\dac_ff[8].dac_state_n_ff.E ),
    .Q(\dac_ff[8].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[8].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[8].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[8].dac_state_p_ff.D ),
    .E(\dac_ff[8].dac_state_n_ff.E ),
    .Q(\dac_ff[8].dac_state_p_ff.Q )
  );
  (* hdlname = "dac_ff[9].dac_state_n_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[9].dac_state_n_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[9].dac_state_n_ff.D ),
    .E(\dac_ff[9].dac_state_n_ff.E ),
    .Q(\dac_ff[9].dac_state_n_ff.Q )
  );
  (* hdlname = "dac_ff[9].dac_state_p_ff dffe" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:14.12-14.46" *)
  EDFD2LVT \dac_ff[9].dac_state_p_ff.dffe  (
    .CP(clk_update),
    .D(\dac_ff[9].dac_state_p_ff.D ),
    .E(\dac_ff[9].dac_state_n_ff.E ),
    .Q(\dac_ff[9].dac_state_p_ff.Q )
  );
endmodule

(* keep_hierarchy =  1  *)
(* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/sampdriver.v:5.1-36.10" *)
(* dont_touch = "true" *)
(* hdlname = "sampdriver" *)
module sampdriver(clk_in, clk_out, clk_out_b);
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/sampdriver.v:6.17-6.23" *)
  input clk_in;
  wire clk_in;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/sampdriver.v:7.17-7.24" *)
  output clk_out;
  wire clk_out;
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/sampdriver.v:8.17-8.26" *)
  output clk_out_b;
  wire clk_out_b;
  (* hdlname = "clk_buf buf_cell" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:33.13-33.36" *)
  BUFFD2LVT \clk_buf.buf_cell  (
    .I(clk_in),
    .Z(clk_out)
  );
  (* hdlname = "clk_inv inv_cell" *)
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/kcaisley/OpenROAD-flow-scripts/flow/designs/src/frida/cells_tsmc65.v:42.12-42.36" *)
  INVD2LVT \clk_inv.inv_cell  (
    .I(clk_in),
    .ZN(clk_out_b)
  );
endmodule
