setup schematiccolors set -wire blue
setup schematiccolors set -graphic black
setup schematiccolors set -background white
setup schematiccolors set -selection orange
setup schematiccolors set -minorgrid grey
setup schematiccolors set -selectionbox lightorange
setup schematiccolors set -portinstance #bf0000
setup schematiccolors set -portshape maroon
setup schematiccolors set -porttext blue
setup schematiccolors set -netlabel purple
setup schematiccolors set -textlabel black
setup schematiccolors set -cellname #00cc66
setup schematiccolors set -instancename #d9cc00
setup schematiccolors set -property grey
setup schematiccolors set -hiddenproperty silver
