; `xyce` Sim Input for `hdl21.sim.data.tb_mos_ibias_nch_150nm`
; Generated by `vlsirtools.XyceNetlister`
; 
; Anonymous `circuit.Package`
; Generated by `vlsirtools.XyceNetlister`
; 

.SUBCKT tb_mos_ibias_nch_150nm
+ VSS 
; No parameters

xdut
+ VDS VGS VSS VBS 
+ sky130_fd_pr__nfet_01v8_lvt
+ PARAMS: w={0.5} l={0.15} nf={1} 

vVDS_src
+ VDS VSS 
+ dc {0} 
+ ac {0} 
+ ; No parameters

vVGS_src
+ VGS VSS 
+ dc {0} 
+ ac {0} 
+ ; No parameters

vVBS_src
+ VBS VSS 
+ dc {0} 
+ ac {0} 
+ ; No parameters

.ENDS

xtop 0 tb_mos_ibias_nch_150nm ; Top-Level DUT 

.lib /tools/kits/SKY/sky130A/libs.tech/ngspice/sky130.lib.spice tt
.save @m.xtop.xdut.msky130_fd_pr__nfet_01v8_lvt[gm]
.save @m.xtop.xdut.msky130_fd_pr__nfet_01v8_lvt[gds]
.save @m.xtop.xdut.msky130_fd_pr__nfet_01v8_lvt[cgg]
.save @m.xtop.xdut.msky130_fd_pr__nfet_01v8_lvt[cdd]
.save @m.xtop.xdut.msky130_fd_pr__nfet_01v8_lvt[cdb]
.save all
.param _dummy_21202_=1 

.dc _dummy_21202_ 1 1 1 

.print dc format=csv v(*) i(*) 

.end 

