setup schematiccolors set -wire #3ac0ff
setup schematiccolors set -graphic #00cc66
setup schematiccolors set -photonicnets #ff8000
setup schematiccolors set -background black
setup schematiccolors set -selection yellow
setup schematiccolors set -minorgrid grey40
setup schematiccolors set -majorgrid white
setup schematiccolors set -selectionbox white
setup schematiccolors set -portinstance red
setup schematiccolors set -portshape red
setup schematiccolors set -porttext red
setup schematiccolors set -netlabel #3ac0ff
setup schematiccolors set -textlabel red
setup schematiccolors set -cellname #00cc66
setup schematiccolors set -instancename #d9cc00
setup schematiccolors set -property #fe8000
setup schematiccolors set -hiddenproperty #7f7f7f
