"""Generate tikz-timing figures from four binary ADC sequencer rows.

Run from the repository root with ``uv run python docs/images/sequences/render.py``.
Then run ``make -C docs sequences`` to render the seven PEX recipes as PDFs.
Other recipes can be passed by name, by four binary CLI arguments, or to render().
"""

from __future__ import annotations

import argparse
import math
import re
import sys
from itertools import groupby
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from flow.adc import sequences

PRE_SYMBOLS = 4  # Show the end of the preceding period.
EXTRA_SYMBOLS = 8  # Show the beginning of the following period.
OUT = Path(__file__).resolve().parent
# The seven timings used by frida1_sequence and frida2_sequence in flow/adc/sim.py.
PEX_NAMES = (
    "symbol160_init4_samp20_comp11110000_logic00001111",
    "symbol160_init4_samp20_comp11110000_logic10000111",
    "symbol160_init4_samp20_comp11111000_logic10000111",
    "symbol160_init4_samp20_comp11111000_logic11000011",
    "symbol160_init4_samp20_comp11111100_logic11000011",
    "symbol160_init4_samp20_comp11111100_logic11100001",
    "symbol160_init4_samp20_comp11111110_logic11100001",
)
CATALOGUE = dict(sequences.SEQUENCES)
RECIPES = {f"comp{name.split('_comp', 1)[1]}": CATALOGUE[name] for name in PEX_NAMES}
ROWS = ("init", "samp", "comp", "logic")


def tick_symbols(sequence: sequences.AdcSequence) -> int:
    """Show roughly 12 ticks per sequence, with binary-friendly spacing."""
    return 2 ** max(0, round(math.log2(len(sequence.init) / 12)))


def repeated_rows(sequence: sequences.AdcSequence) -> dict[str, str]:
    rows = {}
    for name in ROWS:
        row = getattr(sequence, name)
        rows[name] = row[-PRE_SYMBOLS:] + row + row[:EXTRA_SYMBOLS]
    return rows


def tikz_timing_wave(row: str) -> str:
    """Encode binary runs with tikz-timing's native H and L characters."""
    return " ".join(f"{sum(1 for _ in group)}{'H' if bit == '1' else 'L'}" for bit, group in groupby(row))


def tikz_timing_arrows(rows: dict[str, str], row_distance: float) -> str:
    """Place triangular arrows along selected H/L transitions."""
    arrows = []
    for row_index, name in enumerate(ROWS):
        if name in ("init", "samp"):
            continue
        row = rows[name]
        for symbol in range(1, len(row)):
            if row[symbol] == row[symbol - 1]:
                continue
            if name == "logic" and row[symbol] == "0":
                continue
            y = -row_index * row_distance
            start, stop = (y, y + 1) if row[symbol] == "1" else (y + 1, y)
            arrows.append(f"  \\draw[edge arrow] ({symbol},{start:g}) -- ({symbol},{stop:g});")
    return "\n".join(arrows)


def tikz_timing_source(sequence: sequences.AdcSequence) -> str:
    rows = repeated_rows(sequence)
    period = len(sequence.init)
    end = period + EXTRA_SYMBOLS
    x_scale = 14 / (end + PRE_SYMBOLS)
    ticks = list(range(0, period + 1, tick_symbols(sequence)))
    if ticks[-1] != period:
        ticks.append(period)
    tick_list = ",".join(str(tick) for tick in ticks)
    guide_list = ",".join(str(symbol) for symbol in range(0, end + 1, 4))
    row_distance = 1.75
    table_rows = "\n".join(f"  {name} & {tikz_timing_wave(rows[name])} \\\\" for name in ROWS)
    arrows = tikz_timing_arrows(rows, row_distance)
    arrow_styles = r"""\usetikzlibrary{arrows.meta,decorations.markings}
\tikzset{
  edge arrow/.style={
    draw=black,line width=0.85pt,
    postaction={decorate},
    decoration={markings,
      mark=at position 0.7 with {\arrow{Triangle[length=3pt,width=2.4pt]}}}
  }
}"""
    return rf"""% Generated by docs/images/sequences/render.py from flow/adc/sequences.py.
% Regenerate: uv run python docs/images/sequences/render.py; make -C docs sequences
\documentclass[tikz,border=6pt]{{standalone}}
\usepackage{{tikz-timing}}
{arrow_styles}
\usepackage{{xcolor}}
\definecolor{{NordBlue}}{{HTML}}{{5E81AC}}
\definecolor{{NordPanel}}{{HTML}}{{ECEFF4}}
\definecolor{{NordGuide}}{{HTML}}{{D8DEE9}}
\definecolor{{NordRed}}{{HTML}}{{BF616A}}
\begin{{document}}
\begin{{tikztimingtable}}[
  timing/xunit={x_scale:.5f}cm,
  timing/yunit=0.55cm,
  timing/rowdist={row_distance:g},
  timing/coldist=2,
  timing/slope=0,
  timing/name/.append style={{anchor=east,yshift=0.275cm,font=\ttfamily\small,text=NordBlue}},
  draw=black,line width=0.85pt]
{table_rows}
  \extracode
  \begin{{pgfonlayer}}{{background}}
    \foreach \row in {{0,1,2,3}} {{
      \pgfmathsetmacro{{\base}}{{-\row*{row_distance:g}}}
      \foreach \level in {{0,1}} {{
        \pgfmathsetmacro{{\guideheight}}{{\base+\level}}
        \draw[NordGuide,densely dotted,line width=0.5pt] (0,\guideheight) -- ({end + PRE_SYMBOLS},\guideheight);
      }}
    }}
    \foreach \sym in {{{guide_list}}} {{
      \pgfmathsetmacro{{\pos}}{{{PRE_SYMBOLS}+\sym}}
      \draw[NordPanel,line width=0.35pt] (\pos,1.2) -- (\pos,-5.65);
    }}
  \end{{pgfonlayer}}
  \draw[NordRed,dashed,line width=0.8pt] ({PRE_SYMBOLS},1.2) -- ({PRE_SYMBOLS},-5.65);
  \draw[NordRed,dashed,line width=0.8pt] ({PRE_SYMBOLS + period},1.2) -- ({PRE_SYMBOLS + period},-5.65);
{arrows}
  \foreach \sym in {{{tick_list}}} {{
    \pgfmathsetmacro{{\pos}}{{{PRE_SYMBOLS}+\sym}}
    \node[anchor=north,font=\rmfamily\scriptsize] at (\pos,-5.8) {{\sym}};
  }}
\end{{tikztimingtable}}
\end{{document}}
"""


def render(
    sequence: sequences.AdcSequence,
    name: str,
    *,
    output_dir: Path = OUT,
) -> None:
    """Write standalone tikz-timing TeX for any AdcSequence."""
    if not re.fullmatch(r"[A-Za-z0-9_-]+", name):
        raise ValueError("name must contain only letters, digits, underscores, or hyphens")
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / f"{name}.tex").write_text(tikz_timing_source(sequence))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sequence", help="name of an AdcSequence in flow.adc.sequences")
    parser.add_argument("--name", help="output filename prefix for one selected sequence")
    parser.add_argument("--output-dir", type=Path, default=OUT)
    for row in ROWS:
        parser.add_argument(f"--{row}", help=f"binary {row.upper()} pattern")
    args = parser.parse_args()
    raw = {row: getattr(args, row) for row in ROWS}
    if any(value is not None for value in raw.values()):
        if args.sequence or any(value is None for value in raw.values()):
            parser.error("provide all four binary rows, without --sequence")
        selected = {args.name or "custom": sequences.AdcSequence(**raw)}
    elif args.sequence:
        sequence = getattr(sequences, args.sequence, None)
        if not isinstance(sequence, sequences.AdcSequence):
            parser.error(f"unknown AdcSequence: {args.sequence}")
        selected = {args.name or args.sequence: sequence}
    else:
        if args.name:
            parser.error("--name requires --sequence or four binary rows")
        selected = RECIPES
    for name, sequence in selected.items():
        render(sequence, name, output_dir=args.output_dir)


if __name__ == "__main__":
    main()
