"""Backend-neutral result I/O, numerical analysis, and plotting."""

from .adc import (
    analyze_adc,
    analyze_adc_code_density,
    analyze_adc_decision_paths,
    analyze_adc_distribution,
    analyze_adc_dynamic,
    analyze_adc_dynamic_sweep,
    analyze_adc_endpoint_linearity,
    analyze_adc_transfer,
)
from .blocks import analyze_block, analyze_cdac, analyze_comparator, analyze_sampler
from .io import (
    parameter_digest,
    parse_spectre_nutascii,
    read_adc_conversions,
    read_run,
    to_json_data,
)
from .measure import (
    analyze_charge_injection,
    analyze_crossings,
    analyze_delay,
    analyze_edge_samples,
    analyze_offset,
    analyze_power,
    analyze_settling,
    analyze_spectrum,
    analyze_statistics,
    analyze_waveform,
)
from .models import (
    AdcConversion,
    AdcSettings,
    AnalysisKind,
    AnalysisPlan,
    AnalysisReport,
    AnalysisRequest,
    AnalysisResult,
    AnalysisSpec,
    BackendKind,
    BlockKind,
    DataColumn,
    DataTable,
    Metric,
    PlotArtifacts,
    PlotKind,
    PlotRequest,
    PlotSpec,
    RunData,
    SourceFormat,
    SourceSpec,
    StatisticsSettings,
    WaveformSettings,
)
from .plot import render_plot
from .runner import run_analysis_plan

__all__ = [
    "AdcConversion",
    "AdcSettings",
    "AnalysisKind",
    "AnalysisPlan",
    "AnalysisReport",
    "AnalysisRequest",
    "AnalysisResult",
    "AnalysisSpec",
    "BackendKind",
    "BlockKind",
    "DataColumn",
    "DataTable",
    "Metric",
    "PlotArtifacts",
    "PlotKind",
    "PlotRequest",
    "PlotSpec",
    "RunData",
    "SourceFormat",
    "SourceSpec",
    "StatisticsSettings",
    "WaveformSettings",
    "analyze_adc",
    "analyze_adc_code_density",
    "analyze_adc_decision_paths",
    "analyze_adc_distribution",
    "analyze_adc_dynamic",
    "analyze_adc_dynamic_sweep",
    "analyze_adc_endpoint_linearity",
    "analyze_adc_transfer",
    "analyze_block",
    "analyze_cdac",
    "analyze_charge_injection",
    "analyze_comparator",
    "analyze_crossings",
    "analyze_delay",
    "analyze_edge_samples",
    "analyze_offset",
    "analyze_power",
    "analyze_sampler",
    "analyze_settling",
    "analyze_spectrum",
    "analyze_statistics",
    "analyze_waveform",
    "parameter_digest",
    "parse_spectre_nutascii",
    "read_adc_conversions",
    "read_run",
    "render_plot",
    "run_analysis_plan",
    "to_json_data",
]
