# CDL netlist generation for core design
# Generates CDL with power rails and all connectivity

write_cdl -masters "$::env(HOME)/OpenROAD-flow-scripts/flow/platforms/tsmc65/spice/tcbn65lplvt_200a.spi $::env(HOME)/frida/spice/adc.cdl $::env(HOME)/OpenROAD-flow-scripts/flow/platforms/tsmc65/spice/fillers.cdl" \
  $::env(RESULTS_DIR)/6_final.cdl

# Strip all filler and decap instances from CDL
exec grep -Ev "XFILLER.*FILL1LVT|XFILLER.*DCAPLVT|XFILLER.*DCAP4LVT|XFILLER.*DCAP8LVT|XFILLER.*DCAP16LVT|XFILLER.*DCAP32LVT|XFILLER.*DCAP64LVT" $::env(RESULTS_DIR)/6_final.cdl > $::env(RESULTS_DIR)/6_final_nofill.cdl
exec mv $::env(RESULTS_DIR)/6_final_nofill.cdl $::env(RESULTS_DIR)/6_final.cdl

# Insert .INCLUDE statement for ADC hierarchy at the beginning of the file
set cdl_content [exec cat $::env(RESULTS_DIR)/6_final.cdl]
set include_header "* CDL Netlist generated by OpenROAD\n*\n* Include files for hierarchy\n.INCLUDE \"adc.cdl\"\n\n"
set fd [open $::env(RESULTS_DIR)/6_final.cdl w]
puts -nonewline $fd $include_header
puts -nonewline $fd $cdl_content
close $fd

# Add analog pins (vin_p vin_n vdd_a vss_a vdd_d vss_d vdd_dac vss_dac) to the .SUBCKT frida_core port list
# Find the last line of the .SUBCKT frida_core definition (line starting with +) and append the analog pins
exec sed -i {/^\.SUBCKT frida_core/,/^[^+]/{s/^\(+.*[^ ]\)$/\1 vin_p vin_n vdd_a vss_a vdd_d vss_d vdd_dac vss_dac/; t; b}} $::env(RESULTS_DIR)/6_final.cdl

# Copy CDL to frida/spice directory
exec cp $::env(RESULTS_DIR)/6_final.cdl $::env(HOME)/frida/spice/core.cdl
puts "Copied CDL to $::env(HOME)/frida/spice/core.cdl (filler and decap instances removed, analog pins added)"
